array_width = 60
attr_fn_like_width = 60
chain_width = 60
disable_all_formatting = false
edition = "2021"
fn_call_width = 60
force_explicit_abi = true
hard_tabs = false
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 60
merge_derives = false
newline_style = "Unix"
remove_nested_parens = true
reorder_modules = true
short_array_element_width_threshold = 5
single_line_if_else_max_width = 60
struct_lit_width = 5
struct_variant_width = 5
tab_spaces = 2
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true