[package]
name = "kubox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kube = { version = "0", default-features = false, features = ["client", "runtime", "rustls-tls"] }
k8s-openapi = { version = "0.16", features = ["v1_23"] }
async-trait = "0.1"
tokio = { version = "1.23", features = ["rt"] }
futures = "0.3"
serde = "1.0"
tracing = "0.1"