apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }} 
  labels:
  {{- include "tedep.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
