apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "tedep.controller.fullname" . }}
  labels:
    {{- include "tedep.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
- apiGroups: ["tedep.quantum-box.com"]
  resources: ["terraformresources"]
  verbs: ["list", "watch", "patch"]
