apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "tedep.controller.fullname" . }}
  labels:
    {{- include "tedep.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "tedep.controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "tedep.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
