apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.controller.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "tedep.controller.fullname" .}}
  annotations:
  {{- range $key, $value := .Values.controller.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    {{- include "tedep.labels" (dict "context" . "component" .Values.controller.name "name" .Values.controller.name) | nindent 4 }}
  {{- range $key, $value := .Values.controller.serviceAccount.labels }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}