name: rust ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - run: cargo check
    - run: rustup component add rustfmt
    - run: rustup component add clippy
    - run: cargo fmt --all -- --check
    - run: cargo build
    - run: cargo test
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: -- -D clippy::all -D clippy::cargo
